#!/usr/bin/env python

# -*- coding: utf-8 -*-

import random
import unittest
import psycopg2

SERVICE_BASE = 'http://dnsdev2.cm3:55555/op'

if __name__ == '__main__':
    from jsonrpc import ServiceProxy
    import sys

    service = ServiceProxy(SERVICE_BASE)

    for item in service.search(sys.argv[1]):
        print item

# vim: ts=4 sw=4 ai et
